import { StyleSheet } from "@react-pdf/renderer";

export const COLORS = {
  indigo: "#30268F",
  ink: "#20212D",
  muted: "#666775",
  border: "#E3E3EA",
  softBg: "#F7F7FA",
  softPurple: "#F4F2FF",
  warm: "#ED8300",
  warmBg: "#FFF8EF",
  green: "#2F7D5B",
  white: "#FFFFFF",
};

export const pdfStyles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: COLORS.white,
    paddingTop: 30,
    paddingBottom: 34,
    paddingLeft: 40,
    paddingRight: 40,
    fontFamily: "Helvetica",
    color: COLORS.ink,
    fontSize: 10,
    lineHeight: 1.5,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  brandMark: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  brandBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: COLORS.indigo,
    alignItems: "center",
    justifyContent: "center",
  },
  brandLetter: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: "bold",
  },
  brandText: {
    fontSize: 13,
    fontWeight: "bold",
    color: COLORS.indigo,
    letterSpacing: -0.3,
  },
  orgText: {
    fontSize: 9,
    color: COLORS.muted,
    fontWeight: "medium",
  },
  metadataRow: {
    flexDirection: "row",
    paddingTop: 14,
    paddingBottom: 2,
  },
  metadataCol: {
    flex: 1,
  },
  metadataLabel: {
    fontSize: 7.5,
    letterSpacing: 0.6,
    color: COLORS.muted,
    marginBottom: 3,
    textTransform: "uppercase" as const,
  },
  metadataValue: {
    fontSize: 10.5,
    fontWeight: "bold",
    color: COLORS.ink,
  },
  section: {
    marginTop: 18,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: COLORS.ink,
    marginBottom: 10,
  },
  hero: {
    marginTop: 16,
    flexDirection: "row",
    backgroundColor: COLORS.softBg,
    borderRadius: 10,
    padding: 20,
    alignItems: "center",
  },
  heroLeft: {
    flex: 1,
    paddingRight: 20,
  },
  heroEyebrow: {
    fontSize: 8,
    letterSpacing: 0.8,
    color: COLORS.indigo,
    marginBottom: 6,
    textTransform: "uppercase" as const,
  },
  heroName: {
    fontSize: 26,
    fontWeight: "bold",
    color: COLORS.ink,
    lineHeight: 1.1,
  },
  heroPill: {
    marginTop: 8,
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 11,
    paddingRight: 11,
    backgroundColor: COLORS.warmBg,
    borderColor: "#F0C79A",
  },
  heroPillText: {
    fontSize: 9,
    fontWeight: "bold",
    color: COLORS.warm,
  },
  heroDescription: {
    marginTop: 10,
    fontSize: 9,
    lineHeight: 1.5,
    color: COLORS.muted,
    maxWidth: 420,
  },
  heroRight: {
    minWidth: 128,
    alignItems: "center",
  },
  peakPill: {
    marginTop: 8,
    borderRadius: 999,
    borderWidth: 1,
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: COLORS.softPurple,
    borderColor: "#D9D4F5",
    alignItems: "center",
  },
  peakPillText: {
    fontSize: 7.5,
    fontWeight: "bold",
    color: COLORS.indigo,
  },
  scheduleRow: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    marginTop: 12,
    overflow: "hidden",
  },
  scheduleCol: {
    flex: 1,
    paddingTop: 11,
    paddingBottom: 11,
    paddingLeft: 16,
    paddingRight: 16,
  },
  scheduleDivider: {
    width: 1,
    backgroundColor: COLORS.border,
  },
  scheduleLabel: {
    fontSize: 8,
    color: COLORS.muted,
    marginBottom: 3,
  },
  scheduleValue: {
    fontSize: 12,
    fontWeight: "bold",
    color: COLORS.ink,
  },
  twoCol: {
    flexDirection: "row",
    gap: 12,
    marginTop: 12,
  },
  panel: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  panelTitle: {
    fontSize: 10.5,
    fontWeight: "bold",
    marginBottom: 8,
  },
  bulletRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 5,
  },
  bulletDot: {
    width: 5,
    height: 5,
    borderRadius: 999,
    marginTop: 5,
    marginRight: 8,
  },
  bulletText: {
    fontSize: 9,
    lineHeight: 1.4,
    color: COLORS.ink,
    flex: 1,
  },
  stepsSection: {
    marginTop: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#D9D4F5",
    backgroundColor: COLORS.softPurple,
    padding: 14,
  },
  stepsTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: COLORS.indigo,
    marginBottom: 10,
  },
  stepsRow: {
    flexDirection: "row",
  },
  stepCol: {
    flex: 1,
    paddingLeft: 10,
    paddingRight: 10,
  },
  stepBorder: {
    width: 1,
    backgroundColor: "#D9D4F5",
  },
  stepNumberCircle: {
    width: 20,
    height: 20,
    borderRadius: 999,
    backgroundColor: COLORS.indigo,
    alignItems: "center",
    justifyContent: "center",
  },
  stepNumber: {
    fontSize: 8.5,
    fontWeight: "bold",
    color: COLORS.white,
  },
  stepText: {
    fontSize: 8,
    lineHeight: 1.4,
    color: COLORS.ink,
    marginTop: 5,
  },
  rhythmSection: {
    marginTop: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    padding: 14,
  },
  rhythmTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: COLORS.ink,
    marginBottom: 14,
  },
  rhythmRow: {
    flexDirection: "row",
  },
  rhythmCol: {
    flex: 1,
    alignItems: "center",
  },
  rhythmDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  rhythmTime: {
    fontSize: 8.5,
    fontWeight: "bold",
    color: COLORS.ink,
    marginTop: 5,
  },
  rhythmLabel: {
    fontSize: 7.5,
    fontWeight: "bold",
    color: COLORS.indigo,
    marginTop: 2,
  },
  rhythmDesc: {
    fontSize: 6.5,
    color: COLORS.muted,
    marginTop: 2,
    textAlign: "center" as const,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
    paddingTop: 9,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  footerText: {
    fontSize: 7.5,
    color: COLORS.muted,
  },
  pageTwoHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  pageTwoIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  pageTwoName: {
    fontSize: 9.5,
    fontWeight: "bold",
    color: COLORS.ink,
  },
  pageTwoPill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 8,
    paddingRight: 8,
    backgroundColor: COLORS.warmBg,
    borderColor: "#F0C79A",
  },
  pageTwoPillText: {
    fontSize: 7,
    fontWeight: "bold",
    color: COLORS.warm,
  },
  heading2: {
    marginTop: 20,
    marginBottom: 4,
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.ink,
  },
  heading2Sub: {
    marginTop: 0,
    marginBottom: 16,
    fontSize: 8.5,
    color: COLORS.muted,
  },
  recGrid: {
    flexDirection: "row",
    gap: 18,
  },
  recCol: {
    flex: 1,
  },
  recItem: {
    marginBottom: 14,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  recRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  recNumberBadge: {
    width: 18,
    height: 18,
    borderRadius: 5,
    backgroundColor: COLORS.softPurple,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 9,
  },
  recNumber: {
    fontSize: 8,
    fontWeight: "bold",
    color: COLORS.indigo,
  },
  recTitle: {
    fontSize: 10,
    fontWeight: "bold",
    color: COLORS.ink,
    marginBottom: 3,
  },
  recDesc: {
    fontSize: 8,
    lineHeight: 1.45,
    color: COLORS.muted,
  },
  notice: {
    marginTop: 18,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#F0C79A",
    backgroundColor: COLORS.warmBg,
    padding: 12,
  },
  noticeTitle: {
    fontSize: 9,
    fontWeight: "bold",
    color: COLORS.warm,
    marginBottom: 4,
  },
  noticeBody: {
    fontSize: 8,
    lineHeight: 1.45,
    color: COLORS.muted,
  },
});

export const pagePadding = { top: 36, right: 40, bottom: 40, left: 40 };
