export interface CountryCode {
  name: string;
  code: string;
  dial: string;
  /** Maximum digits for local phone numbers (excluding country code). */
  maxLength: number;
  /** Minimum digits for local phone numbers (excluding country code). */
  minLength: number;
}

// Curated list of countries with their dial codes and local number length rules.
// India is placed first as the primary locale.
export const COUNTRY_CODES: CountryCode[] = [
  { name: "India", code: "IN", dial: "+91", maxLength: 10, minLength: 10 },
  { name: "United States", code: "US", dial: "+1", maxLength: 10, minLength: 10 },
  { name: "United Kingdom", code: "GB", dial: "+44", maxLength: 10, minLength: 10 },
  { name: "Canada", code: "CA", dial: "+1", maxLength: 10, minLength: 10 },
  { name: "Australia", code: "AU", dial: "+61", maxLength: 9, minLength: 9 },
  { name: "United Arab Emirates", code: "AE", dial: "+971", maxLength: 9, minLength: 9 },
  { name: "Saudi Arabia", code: "SA", dial: "+966", maxLength: 9, minLength: 9 },
  { name: "Singapore", code: "SG", dial: "+65", maxLength: 8, minLength: 8 },
  { name: "Germany", code: "DE", dial: "+49", maxLength: 11, minLength: 10 },
  { name: "France", code: "FR", dial: "+33", maxLength: 9, minLength: 9 },
  { name: "Italy", code: "IT", dial: "+39", maxLength: 10, minLength: 10 },
  { name: "Spain", code: "ES", dial: "+34", maxLength: 9, minLength: 9 },
  { name: "Netherlands", code: "NL", dial: "+31", maxLength: 9, minLength: 9 },
  { name: "Switzerland", code: "CH", dial: "+41", maxLength: 9, minLength: 9 },
  { name: "Sweden", code: "SE", dial: "+46", maxLength: 9, minLength: 9 },
  { name: "Norway", code: "NO", dial: "+47", maxLength: 8, minLength: 8 },
  { name: "Denmark", code: "DK", dial: "+45", maxLength: 8, minLength: 8 },
  { name: "Japan", code: "JP", dial: "+81", maxLength: 10, minLength: 10 },
  { name: "China", code: "CN", dial: "+86", maxLength: 11, minLength: 11 },
  { name: "South Korea", code: "KR", dial: "+82", maxLength: 10, minLength: 9 },
  { name: "Brazil", code: "BR", dial: "+55", maxLength: 11, minLength: 10 },
  { name: "Mexico", code: "MX", dial: "+52", maxLength: 10, minLength: 10 },
  { name: "Argentina", code: "AR", dial: "+54", maxLength: 10, minLength: 10 },
  { name: "South Africa", code: "ZA", dial: "+27", maxLength: 9, minLength: 9 },
  { name: "Egypt", code: "EG", dial: "+20", maxLength: 10, minLength: 10 },
  { name: "Nigeria", code: "NG", dial: "+234", maxLength: 10, minLength: 10 },
  { name: "Kenya", code: "KE", dial: "+254", maxLength: 9, minLength: 9 },
  { name: "New Zealand", code: "NZ", dial: "+64", maxLength: 9, minLength: 8 },
  { name: "Malaysia", code: "MY", dial: "+60", maxLength: 9, minLength: 9 },
  { name: "Indonesia", code: "ID", dial: "+62", maxLength: 11, minLength: 8 },
  { name: "Thailand", code: "TH", dial: "+66", maxLength: 9, minLength: 9 },
  { name: "Philippines", code: "PH", dial: "+63", maxLength: 10, minLength: 10 },
  { name: "Vietnam", code: "VN", dial: "+84", maxLength: 10, minLength: 9 },
  { name: "Turkey", code: "TR", dial: "+90", maxLength: 10, minLength: 10 },
  { name: "Russia", code: "RU", dial: "+7", maxLength: 10, minLength: 10 },
  { name: "Ukraine", code: "UA", dial: "+380", maxLength: 9, minLength: 9 },
  { name: "Poland", code: "PL", dial: "+48", maxLength: 9, minLength: 9 },
  { name: "Portugal", code: "PT", dial: "+351", maxLength: 9, minLength: 9 },
  { name: "Belgium", code: "BE", dial: "+32", maxLength: 9, minLength: 8 },
  { name: "Austria", code: "AT", dial: "+43", maxLength: 10, minLength: 9 },
  { name: "Ireland", code: "IE", dial: "+353", maxLength: 9, minLength: 7 },
  { name: "Greece", code: "GR", dial: "+30", maxLength: 10, minLength: 10 },
  { name: "Czech Republic", code: "CZ", dial: "+420", maxLength: 9, minLength: 9 },
  { name: "Israel", code: "IL", dial: "+972", maxLength: 9, minLength: 8 },
  { name: "Qatar", code: "QA", dial: "+974", maxLength: 8, minLength: 8 },
  { name: "Kuwait", code: "KW", dial: "+965", maxLength: 8, minLength: 8 },
  { name: "Bahrain", code: "BH", dial: "+973", maxLength: 8, minLength: 8 },
  { name: "Oman", code: "OM", dial: "+968", maxLength: 8, minLength: 8 },
  { name: "Jordan", code: "JO", dial: "+962", maxLength: 9, minLength: 9 },
  { name: "Lebanon", code: "LB", dial: "+961", maxLength: 8, minLength: 7 },
  { name: "Iraq", code: "IQ", dial: "+964", maxLength: 10, minLength: 9 },
  { name: "Iran", code: "IR", dial: "+98", maxLength: 10, minLength: 10 },
  { name: "Pakistan", code: "PK", dial: "+92", maxLength: 10, minLength: 10 },
  { name: "Bangladesh", code: "BD", dial: "+880", maxLength: 10, minLength: 10 },
  { name: "Sri Lanka", code: "LK", dial: "+94", maxLength: 9, minLength: 9 },
  { name: "Nepal", code: "NP", dial: "+977", maxLength: 10, minLength: 10 },
  { name: "Bhutan", code: "BT", dial: "+975", maxLength: 8, minLength: 8 },
  { name: "Maldives", code: "MV", dial: "+960", maxLength: 7, minLength: 7 },
  { name: "Afghanistan", code: "AF", dial: "+93", maxLength: 9, minLength: 9 },
  { name: "Myanmar", code: "MM", dial: "+95", maxLength: 10, minLength: 8 },
  { name: "Cambodia", code: "KH", dial: "+855", maxLength: 9, minLength: 8 },
  { name: "Laos", code: "LA", dial: "+856", maxLength: 10, minLength: 8 },
  { name: "Mongolia", code: "MN", dial: "+976", maxLength: 8, minLength: 8 },
  { name: "Kazakhstan", code: "KZ", dial: "+7", maxLength: 10, minLength: 10 },
  { name: "Uzbekistan", code: "UZ", dial: "+998", maxLength: 9, minLength: 9 },
  { name: "Chile", code: "CL", dial: "+56", maxLength: 9, minLength: 8 },
  { name: "Colombia", code: "CO", dial: "+57", maxLength: 10, minLength: 10 },
  { name: "Peru", code: "PE", dial: "+51", maxLength: 9, minLength: 9 },
  { name: "Venezuela", code: "VE", dial: "+58", maxLength: 10, minLength: 10 },
  { name: "Ecuador", code: "EC", dial: "+593", maxLength: 9, minLength: 8 },
  { name: "Bolivia", code: "BO", dial: "+591", maxLength: 8, minLength: 8 },
  { name: "Uruguay", code: "UY", dial: "+598", maxLength: 8, minLength: 8 },
  { name: "Paraguay", code: "PY", dial: "+595", maxLength: 9, minLength: 9 },
  { name: "Cuba", code: "CU", dial: "+53", maxLength: 8, minLength: 8 },
  { name: "Dominican Republic", code: "DO", dial: "+1", maxLength: 10, minLength: 10 },
  { name: "Puerto Rico", code: "PR", dial: "+1", maxLength: 10, minLength: 10 },
  { name: "Jamaica", code: "JM", dial: "+1", maxLength: 10, minLength: 10 },
  { name: "Trinidad and Tobago", code: "TT", dial: "+1", maxLength: 10, minLength: 10 },
  { name: "Panama", code: "PA", dial: "+507", maxLength: 8, minLength: 8 },
  { name: "Costa Rica", code: "CR", dial: "+506", maxLength: 8, minLength: 8 },
  { name: "Guatemala", code: "GT", dial: "+502", maxLength: 8, minLength: 8 },
  { name: "Honduras", code: "HN", dial: "+504", maxLength: 8, minLength: 8 },
  { name: "El Salvador", code: "SV", dial: "+503", maxLength: 8, minLength: 8 },
  { name: "Nicaragua", code: "NI", dial: "+505", maxLength: 8, minLength: 8 },
  { name: "Morocco", code: "MA", dial: "+212", maxLength: 9, minLength: 9 },
  { name: "Algeria", code: "DZ", dial: "+213", maxLength: 9, minLength: 9 },
  { name: "Tunisia", code: "TN", dial: "+216", maxLength: 8, minLength: 8 },
  { name: "Libya", code: "LY", dial: "+218", maxLength: 9, minLength: 9 },
  { name: "Sudan", code: "SD", dial: "+249", maxLength: 9, minLength: 9 },
  { name: "Ethiopia", code: "ET", dial: "+251", maxLength: 9, minLength: 9 },
  { name: "Tanzania", code: "TZ", dial: "+255", maxLength: 9, minLength: 9 },
  { name: "Uganda", code: "UG", dial: "+256", maxLength: 9, minLength: 9 },
  { name: "Ghana", code: "GH", dial: "+233", maxLength: 9, minLength: 9 },
  { name: "Senegal", code: "SN", dial: "+221", maxLength: 9, minLength: 9 },
  { name: "Cameroon", code: "CM", dial: "+237", maxLength: 9, minLength: 9 },
  { name: "Zimbabwe", code: "ZW", dial: "+263", maxLength: 9, minLength: 9 },
  { name: "Zambia", code: "ZM", dial: "+260", maxLength: 9, minLength: 9 },
  { name: "Botswana", code: "BW", dial: "+267", maxLength: 8, minLength: 7 },
  { name: "Fiji", code: "FJ", dial: "+679", maxLength: 7, minLength: 7 },
  { name: "Papua New Guinea", code: "PG", dial: "+675", maxLength: 8, minLength: 8 },
  { name: "Brunei", code: "BN", dial: "+673", maxLength: 7, minLength: 7 },
  { name: "Finland", code: "FI", dial: "+358", maxLength: 10, minLength: 9 },
  { name: "Iceland", code: "IS", dial: "+354", maxLength: 7, minLength: 7 },
  { name: "Luxembourg", code: "LU", dial: "+352", maxLength: 9, minLength: 8 },
  { name: "Malta", code: "MT", dial: "+356", maxLength: 8, minLength: 8 },
  { name: "Cyprus", code: "CY", dial: "+357", maxLength: 8, minLength: 8 },
  { name: "Estonia", code: "EE", dial: "+372", maxLength: 8, minLength: 7 },
  { name: "Latvia", code: "LV", dial: "+371", maxLength: 8, minLength: 8 },
  { name: "Lithuania", code: "LT", dial: "+370", maxLength: 8, minLength: 8 },
  { name: "Slovakia", code: "SK", dial: "+421", maxLength: 9, minLength: 9 },
  { name: "Slovenia", code: "SI", dial: "+386", maxLength: 9, minLength: 8 },
  { name: "Croatia", code: "HR", dial: "+385", maxLength: 9, minLength: 8 },
  { name: "Serbia", code: "RS", dial: "+381", maxLength: 9, minLength: 9 },
  { name: "Romania", code: "RO", dial: "+40", maxLength: 9, minLength: 9 },
  { name: "Bulgaria", code: "BG", dial: "+359", maxLength: 9, minLength: 9 },
  { name: "Hungary", code: "HU", dial: "+36", maxLength: 9, minLength: 9 },
  { name: "Albania", code: "AL", dial: "+355", maxLength: 9, minLength: 9 },
  { name: "North Macedonia", code: "MK", dial: "+389", maxLength: 9, minLength: 8 },
  { name: "Georgia", code: "GE", dial: "+995", maxLength: 9, minLength: 9 },
  { name: "Armenia", code: "AM", dial: "+374", maxLength: 8, minLength: 8 },
  { name: "Azerbaijan", code: "AZ", dial: "+994", maxLength: 9, minLength: 9 },
  { name: "Belarus", code: "BY", dial: "+375", maxLength: 9, minLength: 9 },
  { name: "Moldova", code: "MD", dial: "+373", maxLength: 8, minLength: 8 },
  { name: "Taiwan", code: "TW", dial: "+886", maxLength: 10, minLength: 9 },
  { name: "Hong Kong", code: "HK", dial: "+852", maxLength: 8, minLength: 8 },
  { name: "Macau", code: "MO", dial: "+853", maxLength: 8, minLength: 8 },
  { name: "Kosovo", code: "XK", dial: "+383", maxLength: 9, minLength: 8 },
];

export function getCountryCode(dial: string): CountryCode | undefined {
  return COUNTRY_CODES.find((c) => c.dial === dial);
}

export function getCountryCodeByName(name: string): CountryCode | undefined {
  return COUNTRY_CODES.find((c) => c.name.toLowerCase() === name.toLowerCase());
}
